apiVersion: apps/v1

kind: ReplicaSet

metadata:

  name: flask-app

  labels:

    app: flask-app


spec:

  # modify replicas according to your case

  replicas: 2

  selector:

    matchLabels:

      app: flask-app

  template:

    metadata:

      labels:

        app: flask-app

    spec:

      containers:

      - name: flask-app

        image: derao/flask-app

